baseURL = 'https://montfort.github.io/actividad1_blog/'
languageCode = 'es-MX'
title = 'BLOG'
theme = 'jvm_theme'
defaultContentLanguage = "es"
[markup.goldmark.renderer]
  unsafe = true
[caches]
  [caches.images]
    dir = ':cacheDir/images'